# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=128)),
                ('identidade', models.CharField(max_length=20)),
                ('endere', models.CharField(max_length=128)),
                ('telefone', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=128)),
                ('descri', models.TextField(max_length=128)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField()),
                ('valor', models.CharField(max_length=128)),
                ('tipo', models.BooleanField(default=True, verbose_name='Avista')),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('quantidade', models.IntegerField()),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atendimento.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=128)),
                ('nome', models.CharField(max_length=128)),
                ('endere', models.CharField(max_length=128)),
                ('telefone', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=128)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vendas',
            name='vendendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atendimento.Vendedor'),
        ),
    ]
